version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m -Xms1600m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.m2/
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - run: ls ~/.m2/repository/org/spigotmc/spigot/1.15.2-R0.1-SNAPSHOT >> /dev/null 2>&1 || java -jar BuildTools.jar --rev 1.15.2 >> /dev/null 2>&1
      - run: ls ~/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT >> /dev/null 2>&1 || java -jar BuildTools.jar --rev 1.16.4 >> /dev/null 2>&1
      - run: git clone https://github.com/PaperMC/PaperLib
      - run: git clone https://github.com/Ponclure/Simple-NPC-Framework
      - run: mvn clean install
      - store_artifacts:
          path: target/securitycams-RELEASE-1.0.1-jar-with-dependencies.jar
